---
- name: Install jenkins-job-builder
  pip:
    name: jenkins-job-builder
    virtualenv: '{{ playbook_dir }}/venv'
    virtualenv_python: python2.7
    virtualenv_site_packages: no
- name: Start Minio container
  become: True
  docker_container:
    name: minio
    image: minio/minio
    pull: True
    recreate: True
    command: server /data
    env:
      MINIO_ACCESS_KEY: '{{ project }}'
      MINIO_SECRET_KEY: '{{ project }}'
    published_ports:
      - '{{ minio_port }}:9000'
    volumes:
      - /data/minio:/data
- name: Start Jenkins container
  become: True
  docker_container:
    name: jenkins
    image: ollivier/jenkins
    pull: True
    recreate: True
    published_ports:
      - '{{ jenkins_port }}:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/jenkins:/var/jenkins_home
    links:
      - minio:minio
- name: Configure Minio
  become: True
  command: docker exec jenkins {{ item }}
  with_items:
    - 'mc config host add minio http://minio:{{ minio_port }} {{ project }} {{ project }}'
    - 'mc mb -p minio/{{ project }}'
- name: Wait Jenkins
  pause:
    seconds: 30
- template:
    src: jenkins_jobs.ini.j2
    dest: jenkins_jobs.ini
- template:
    src: run.yaml.j2
    dest: run.yaml
- name: Load Jenkins jobs
  command:
    '{{ playbook_dir }}/venv/bin/jenkins-jobs --conf jenkins_jobs.ini update run.yaml'
- name: Start S3www container
  become: True
  docker_container:
    name: s3www
    image: ollivier/s3www
    pull: True
    recreate: True
    published_ports:
      - '{{ s3www_port }}:8080'
    env:
      ENDPOINT: http://minio:{{ minio_port }}
    links:
      - minio:minio
