---
jenkins_port: 8080
minio_port: 9000
s3www_port: 80
jenkins_user: admin
jenkins_password: admin
project: xtesting
suites:
  - repo: opnfv
    container: xtesting
    tag: latest
    tests:
      - first
      - second
      - third
      - fourth
      - fifth
