#!/bin/bash

download-frozen-image-v2.sh /data/docker/xtesting \
  opnfv/xtesting:latest
git clone https://git.opnfv.org/functest-xtesting /home/debian/functest-xtesting
chown -R 1000:1000 /home/debian/functest-xtesting

exit 0
